# Generated by Django 5.0.4 on 2024-04-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lixeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(help_text='Localização física da lixeira', max_length=255)),
                ('tipo_residuo', models.CharField(choices=[('reciclaveis', 'Recicláveis'), ('organicos', 'Orgânicos'), ('nao_reciclaveis', 'Não Recicláveis')], default='reciclaveis', help_text='Tipo de resíduo aceito pela lixeira', max_length=50)),
                ('capacidade_maxima', models.IntegerField(help_text='Capacidade máxima da lixeira em quilogramas')),
                ('estado_atual', models.CharField(choices=[('vazia', 'Vazia'), ('cheia', 'Cheia'), ('intermediaria', 'Intermediária')], default='vazia', help_text='Estado atual da lixeira', max_length=20)),
                ('data_instalacao', models.DateField(help_text='Data de instalação da lixeira')),
                ('horario_funcionamento', models.CharField(help_text='Horário de funcionamento da lixeira', max_length=50)),
                ('responsavel_manutencao', models.CharField(help_text='Responsável pela manutenção', max_length=100)),
                ('status_manutencao', models.BooleanField(default=False, help_text='Indica se a lixeira requer manutenção')),
            ],
        ),
    ]
