# Generated by Django 5.0.4 on 2024-04-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lixeira',
            name='localizacao',
            field=models.CharField(help_text='Localização física da lixeira em coordenadas', max_length=255),
        ),
    ]
