# Generated by Django 5.0.4 on 2024-04-22 14:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rt_app', '0006_agendamentomanutencao_lixeira_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgendamentoManutencao',
            new_name='Avisos',
        ),
    ]
