# Generated by Django 5.0.4 on 2024-04-22 14:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rt_app', '0007_rename_agendamentomanutencao_avisos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avisos',
            new_name='Aviso',
        ),
    ]
