# Generated by Django 5.0.4 on 2024-04-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rt_app", "0008_rename_avisos_aviso"),
    ]

    operations = [
        migrations.AddField(
            model_name="lixeira",
            name="email",
            field=models.CharField(
                help_text="Email do proprietário", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="lixeira",
            name="domicilio",
            field=models.CharField(
                help_text="Casa, Restaurante, Hospital etc...",
                max_length=255,
                null=True,
            ),
        ),
    ]
