# Generated by Django 5.0.4 on 2024-04-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rt_app', '0002_alter_lixeira_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lixeira',
            name='estado_atual',
            field=models.IntegerField(help_text='Capacidade atual da lixeira em quilogramas'),
        ),
    ]
