# Generated by Django 5.0.4 on 2024-04-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rt_app', '0003_alter_lixeira_estado_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='lixeira',
            name='domicilio',
            field=models.CharField(default='Endereço padrão', help_text='Endereço atrelado à lixeira', max_length=255),
        ),
        migrations.AlterField(
            model_name='lixeira',
            name='estado_atual',
            field=models.IntegerField(help_text='Estado atual da lixeira em quilogramas'),
        ),
    ]
