# Generated by Django 5.0.4 on 2024-04-22 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rt_app', '0005_agendamentomanutencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentomanutencao',
            name='lixeira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rt_app.lixeira'),
        ),
        migrations.AddField(
            model_name='agendamentomanutencao',
            name='motivo',
            field=models.CharField(default='Motivo', help_text='Motivo da manutenção', max_length=200),
        ),
    ]
