# Generated by Django 5.0.4 on 2024-04-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rt_app', '0009_lixeira_email_alter_lixeira_domicilio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lixeira',
            name='horario_funcionamento',
        ),
        migrations.RemoveField(
            model_name='lixeira',
            name='responsavel_manutencao',
        ),
    ]
