# Generated by Django 5.0.4 on 2024-04-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rt_app', '0010_remove_lixeira_horario_funcionamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aviso',
            name='tecnico_responsavel',
        ),
        migrations.AlterField(
            model_name='lixeira',
            name='domicilio',
            field=models.CharField(choices=[('condomminio', 'Condomínio'), ('hospital', 'Hospital'), ('escola', 'Escola/Universidade'), ('restaurante', 'Restaurante')], help_text='Casa, Restaurante, Hospital etc...', max_length=255, null=True),
        ),
    ]
