# Generated by Django 5.0.4 on 2024-04-25 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rt_app', '0011_remove_aviso_tecnico_responsavel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aviso',
        ),
    ]
