# Generated by Django 5.0.4 on 2024-06-06 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rt_app', '0013_lixeira_status_coleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lixeira',
            name='data_instalacao',
            field=models.DateField(auto_now_add=True, help_text='Data de instalação da lixeira'),
        ),
        migrations.AddField(
            model_name='lixeira',
            name='bairro',
            field=models.ForeignKey(help_text='Bairro que a lixeira pertence', null=True, on_delete=django.db.models.deletion.CASCADE, to='rt_app.bairro'),
        ),
    ]
