# Generated by Django 5.0.4 on 2024-06-07 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0005_alter_lixeira_bairro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coletas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lixeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.lixeira')),
            ],
        ),
    ]
