# Generated by Django 5.0.4 on 2024-06-07 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lixeira',
            name='status_coleta',
        ),
        migrations.CreateModel(
            name='Lotada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lixeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.lixeira')),
            ],
        ),
    ]
