# Generated by Django 5.0.4 on 2024-06-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_remove_lixeira_status_coleta_lotada'),
    ]

    operations = [
        migrations.AddField(
            model_name='lixeira',
            name='progresso_atual',
            field=models.FloatField(help_text='Indica o progresso da lixeira (em %)', null=True),
        ),
    ]
