# Generated by Django 5.0.4 on 2024-06-07 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_lixeira_progresso_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lixeira',
            name='bairro',
            field=models.ForeignKey(help_text='Bairro que a lixeira pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lixeira', to='admin_app.bairro'),
        ),
    ]
