# Generated by Django 5.0.4 on 2024-06-08 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_lixeira_coleta_realizada'),
        ('cliente_app', '0003_rename_cliente_manutencao_cliente_manutencao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lixeira',
            name='email',
            field=models.ForeignKey(help_text='Email do proprietário', null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente_app.cliente'),
        ),
    ]
