# Generated by Django 5.0.4 on 2024-06-09 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_rename_email_lixeira_cliente'),
        ('cliente_app', '0004_delete_manutencao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField(auto_now_add=True)),
                ('nota', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Nota de 1 a 5')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='cliente_app.cliente')),
                ('lixeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='admin_app.lixeira')),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_manutencao', models.DateField()),
                ('tempo_manutencao', models.TimeField()),
                ('motivo_manutencao', models.CharField(max_length=255, null=True)),
                ('lixeira', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manutencao', to='admin_app.lixeira')),
            ],
        ),
    ]
