# Generated by Django 5.0.4 on 2024-06-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_manutencao', models.DateField()),
                ('tempo_manutencao', models.TimeField()),
                ('motivo_manutencao', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
