# Generated by Django 5.0.4 on 2024-06-07 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_app', '0002_cliente_manutencao_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manutencao',
            old_name='cliente',
            new_name='cliente_manutencao',
        ),
    ]
