# Generated by Django 5.0.4 on 2024-06-09 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_app', '0003_rename_cliente_manutencao_cliente_manutencao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manutencao',
        ),
    ]
