# Generated by Django 5.0.4 on 2024-06-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coletor',
            name='coletas_realizadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coletor',
            name='peso_coletado',
            field=models.FloatField(default=0),
        ),
    ]
